### ISSUE TITLE
[Outputs] Add alerta output  

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud-infra/delatore#42]
Add integration with apimon alerta to report problems

**Comment by outcatcher** [comment]
Depends on #43

**Comment by outcatcher** [comment]
See https://github.com/alerta/python-alerta-client

**Comment by outcatcher** [comment]
Use service:`test` for testing purposes

**Comment by outcatcher** [comment]
Python `alerta` client is requests-based. It will take too much effort to implement this with aoihttp. Consider using threaded approach in this case.

**Comment by anton-sidelnikov** [comment]
https://alerts.eco.tsi-dev.otc-service.com/

**Comment by outcatcher** [comment]
Need fix
