### ISSUE TITLE
Scenario 1_5 alert

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud-infra/delatore#88]
Check lb_down_test metric, if we have script status differ from 0, then send next type of message:
```
-  LB_DOWN
-  Status: Alerting
-  Alert message: Test script return error: "reason"
```
Request: SELECT count("state") FROM "lb_down_test" WHERE ("reason" != '0') GROUP BY time(1m)

**Comment by outcatcher** [comment]
Add alert when fail count hits 5

**Comment by anton-sidelnikov** [comment]
SELECT count("requests") FROM "lb_down" WHERE ("ok" = 'False') AND $timeFilter GROUP BY time(1m) fill(null), if count > 5 for 5 minutes:
-  LB_DOWN
-  Status: Alerting
-  Alert message: Failed requests are above 5 for host {hostname}
