### ISSUE TITLE
Get job templates last statuses from AWX

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud-infra/delatore#9]

**Comment by outcatcher** [comment]
### Proposal
#### Commands
- `!status awx` to get last execution status of all _scenarios_
- `!status awx:scenario1` to get last status of _scenario_ 1
- `!status awx:test_host` to get last status of `test_host` playbook
- `!status awx:scenario1 5` to get last 5 statuses for scenario1

**Comment by anton-sidelnikov** [comment]
Created branch feature/awx_jobs_status
First task described in file awx_status.py
Then we create a webhook for commads which proposed by Anton K

**Comment by outcatcher** [comment]
Graceful command handling seems to be easier to implement using some bot library, e.g. https://github.com/eternnoir/pyTelegramBotAPI

**Comment by outcatcher** [comment]
I won't recommend `/command` syntax as it provokes clicking on `/command` text, triggering command again

**Comment by outcatcher** [comment]
Use `/status` instead of `!status`, but remember to remove message afterwards

**Comment by outcatcher** [comment]
Or use `/command` and remove message after bot reply
