### ISSUE TITLE
Scenario 3_5 alert

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud-infra/delatore#91]
Check if iscsi disk falls in read only state

Send 1 alert message if only writes returns empty result
Send 2 alert if reads and writes returns empty result

```
- SCCI_HDD_TEST
- Status: Alerting
- Alert message: 1) for "device" allowed only read operations or 2) Cannot read and write any data on "device"
- CPU utilization: current cpu utilization for cpu.system
- Memory utilization: current memory utilization
```

**Comment by lego963** [comment]
Closed by: https://github.com/opentelekomcloud-infra/delatore/pull/105
